### ISSUE TITLE
Lots of errors in Parallel.cpp

### ISSUE THREAD

**Issue by max90727** [delsauce/ArduinoDueParallel#1]
Hi:
Thanks for your code.
I have lots of errors in Parallel.cpp which I have no idea how to fix them. 

Parallel.cpp:40: error: 'PinDescription' does not name a type
 error: 'DataPins' was not declared in this scope
Parallel.cpp:147: error: 'PIO_Configure' was not declared in this scope
Parallel.cpp:151: error: 'AddressPins' was not declared in this scope
Parallel.cpp:166: error: 'ReadPin' was not declared in this scope
Parallel.cpp:174: error: 'WritePin' was not declared in this scope
Parallel.cpp:169: error: 'PIO_Configure' was not declared in this scope
.......
And so on.
I suppose there are some libraries I have to include. Could you tell me what they are?

**Comment by delsauce** [comment]
Did you include Arduino.h in your sketch?

**Comment by max90727** [comment]
Sorry. I didn't watch it clearly. The board I have is Uno, not Due
Anyway, can I have some suggestions on how is this work on Uno?

**Comment by delsauce** [comment]
Yeah, Uno isn't going to work for this...  There is no parallel bus HW in the Uno.  You could write your own library to implement similar features, but it would be completely different.
